name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libpulse-dev \
          libgl1-mesa-dev \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libwayland-dev \
          wayland-protocols \
          libxkbcommon-dev \
          xvfb
          
    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git $HOME/vcpkg
        $HOME/vcpkg/bootstrap-vcpkg.sh
        echo "VCPKG_ROOT=$HOME/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_FEATURE_FLAGS=manifests" >> $GITHUB_ENV
          
    - name: Install Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
        
    - name: Configure CMake
      run: task setup
      
    - name: Build Debug
      run: task build
      
    - name: Build Release  
      run: task release
      
    - name: Run Tests
      run: task test

  build-windows:
    runs-on: windows-2025
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Install Task
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://github.com/go-task/task/releases/latest/download/task_windows_amd64.zip" -OutFile "task.zip"
        New-Item -ItemType Directory -Path "task-temp" -Force
        Expand-Archive -Path task.zip -DestinationPath "task-temp" -Force
        Move-Item -Path "task-temp\task.exe" -Destination C:\Windows\System32\
        
    - name: Install vcpkg dependencies
      run: vcpkg install --triplet x64-windows
      
    - name: Configure CMake
      run: task setup
      
    - name: Build Debug
      run: task build
      
    - name: Build Release
      run: task release
      
    - name: Run Tests
      run: task test